import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useAuth } from '@utils/hooks';
import { useNavigate } from 'react-router-dom';
import { LogOut, Menu } from 'lucide-react';
export const Layout = ({ children }) => {
    const { logout } = useAuth();
    const navigate = useNavigate();
    const [isSidebarOpen, setIsSidebarOpen] = React.useState(true);
    return (_jsxs("div", { className: "flex h-screen bg-gray-100", children: [_jsxs("div", { className: `${isSidebarOpen ? 'w-64' : 'w-20'} sidebar transition-all duration-300 text-white`, children: [_jsx("div", { className: "p-4", children: _jsx("h1", { className: `font-bold text-xl ${!isSidebarOpen && 'text-center'}`, children: "Vakshesa" }) }), _jsxs("nav", { className: "mt-8", children: [_jsx(NavItem, { label: "Dashboard", icon: "\uD83D\uDCCA", onClick: () => navigate('/dashboard'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Users", icon: "\uD83D\uDC65", onClick: () => navigate('/users'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Families", icon: "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67", onClick: () => navigate('/families'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Stalls", icon: "\uD83D\uDED2", onClick: () => navigate('/stalls'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Leaderboard", icon: "\uD83C\uDFC6", onClick: () => navigate('/leaderboard'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Event Settings", icon: "\u2699\uFE0F", onClick: () => navigate('/settings'), collapsed: !isSidebarOpen })] }), _jsx("div", { className: "absolute bottom-4 left-4 right-4", children: _jsxs("button", { onClick: logout, className: "w-40 flex items-center gap-2 bg-white/20 hover:bg-white/30 p-2 rounded transition-colors", children: [_jsx(LogOut, { size: 20 }), isSidebarOpen && _jsx("span", { children: "Logout" })] }) })] }), _jsxs("div", { className: "flex-1 flex flex-col", children: [_jsx("header", { className: "bg-white shadow-sm border-b", children: _jsxs("div", { className: "flex items-center justify-between p-4", children: [_jsx("button", { onClick: () => setIsSidebarOpen(!isSidebarOpen), className: "text-gray-700 hover:text-gray-900", children: _jsx(Menu, { size: 24 }) }), _jsx("div", { className: "text-gray-700", children: _jsx("span", { children: "Admin Panel" }) })] }) }), _jsx("main", { className: "flex-1 overflow-auto p-6", children: children })] })] }));
};
const NavItem = ({ label, icon, onClick, collapsed }) => (_jsxs("button", { onClick: onClick, className: "w-full flex items-center gap-3 px-4 py-3 hover:bg-white/10 transition-colors text-left", children: [_jsx("span", { className: "text-xl", children: icon }), !collapsed && _jsx("span", { children: label })] }));
