import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useAuth } from '@utils/hooks';
import { useNavigate } from 'react-router-dom';
import { LogOut, Menu, LayoutDashboard, Users, UserPlus, Home, ShoppingCart, Trophy, Calendar, Tent, TrendingUp, DollarSign, FileText, Settings, Lock } from 'lucide-react';
export const Layout = ({ children }) => {
    const { logout } = useAuth();
    const navigate = useNavigate();
    const [isSidebarOpen, setIsSidebarOpen] = React.useState(true);
    return (_jsxs("div", { className: "flex h-screen bg-gray-100", children: [_jsxs("div", { className: `${isSidebarOpen ? 'w-64' : 'w-20'} sidebar transition-all duration-300 text-white`, children: [_jsx("div", { className: "p-4", children: _jsx("h1", { className: `font-bold text-xl ${!isSidebarOpen && 'text-center'}`, children: "Vakshesa" }) }), _jsxs("nav", { className: "mt-8", children: [_jsx(NavItem, { label: "Dashboard", icon: _jsx(LayoutDashboard, { size: 20 }), onClick: () => navigate('/dashboard'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Users", icon: _jsx(Users, { size: 20 }), onClick: () => navigate('/users'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Register User", icon: _jsx(UserPlus, { size: 20 }), onClick: () => navigate('/register-user'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Families", icon: _jsx(Home, { size: 20 }), onClick: () => navigate('/families'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Stalls", icon: _jsx(ShoppingCart, { size: 20 }), onClick: () => navigate('/stalls'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Leaderboard", icon: _jsx(Trophy, { size: 20 }), onClick: () => navigate('/leaderboard'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Events", icon: _jsx(Calendar, { size: 20 }), onClick: () => navigate('/events'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Carnival Events", icon: _jsx(Tent, { size: 20 }), onClick: () => navigate('/carnival-events'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Carnival Analytics", icon: _jsx(TrendingUp, { size: 20 }), onClick: () => navigate('/carnival-analytics'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Token Recharge", icon: _jsx(DollarSign, { size: 20 }), onClick: () => navigate('/token-recharge'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Stall Audit", icon: _jsx(FileText, { size: 20 }), onClick: () => navigate('/stall-audit'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Event Settings", icon: _jsx(Settings, { size: 20 }), onClick: () => navigate('/settings'), collapsed: !isSidebarOpen }), _jsx(NavItem, { label: "Change Password", icon: _jsx(Lock, { size: 20 }), onClick: () => navigate('/change-password'), collapsed: !isSidebarOpen })] }), _jsx("div", { className: "absolute bottom-4 left-4 right-4", children: _jsxs("button", { onClick: () => {
                                if (window.confirm('Are you sure you want to logout?')) {
                                    logout();
                                }
                            }, className: `flex items-center gap-2 bg-white/20 hover:bg-white/30 p-3 rounded-lg transition-colors w-full ${!isSidebarOpen ? 'justify-center' : ''}`, children: [_jsx(LogOut, { size: 20 }), isSidebarOpen && _jsx("span", { children: "Logout" })] }) })] }), _jsxs("div", { className: "flex-1 flex flex-col", children: [_jsx("header", { className: "bg-white shadow-sm border-b", children: _jsxs("div", { className: "flex items-center justify-between p-4", children: [_jsx("button", { onClick: () => setIsSidebarOpen(!isSidebarOpen), className: "text-gray-700 hover:text-gray-900", children: _jsx(Menu, { size: 24 }) }), _jsx("div", { className: "text-gray-700", children: _jsx("span", { children: "Admin Panel" }) })] }) }), _jsx("main", { className: "flex-1 overflow-auto p-6", children: children })] })] }));
};
const NavItem = ({ label, icon, onClick, collapsed }) => (_jsxs("button", { onClick: onClick, className: "w-full flex items-center gap-3 px-4 py-3 hover:bg-white/10 transition-colors text-left", children: [icon, !collapsed && _jsx("span", { children: label })] }));
